### ISSUE TITLE
Couchbackup should give a better error message when incorrect creds are used

### ISSUE THREAD

**Issue by tomblench** [cloudant/couchbackup#212]
Currently a zero length backup file results and the output is
```
couchbackup Backup complete - written{"total":0,"err":null} +0ms
```

**Comment by tomblench** [comment]
The original report appears to have been from an old version of couchbackup. With recent versions the error report is
```
ERROR: 401 : HEAD https://XXXXXX:XXXXXX@tomblench.cloudant.com/animaldb/_bulk_get
```

**Comment by ricellis** [comment]
I think this issue needs to dig a little deeper than missing creds though and help provide a bit more user assistance.
Currently in full mode backup the `_bulk_get` check is the first thing that happens and this can be misleading.
Not least because the 404 happens if the database doesn't exist or if it doesn't support `_bulk_get`.
https://github.com/cloudant/couchbackup/blob/master/includes/backup.js#L87

Maybe we should do an additional `HEAD` request to check the existence of the DB and that the creds are valid even before we split between full and shallow mode.
