### ISSUE TITLE
Backup PARALLELISM

### ISSUE THREAD

**Issue by wmbutler** [cloudant/couchbackup#262]
Continuation of #214 

```
ubuntu@cavo_admin:/home/backup$ couchbackup --version
2.3.1
```

```bash
#!/bin/bash

# Couchbackup perfomance options
BUFFERSIZE=10000
MODE="shallow"
PARALLELISM=10

/usr/local/bin/couchbackup --url $URL --buffer-size $BUFFERSIZE --parallelism $PARALLELISM --mode $MODE --log $BASE/$DIR/$DATABASE.log --db $DATABASE > $BASE/$DIR/$DATABASE.json
```

I upgraded the machine I use for backups from 2 procs to 8. It also has a 1 Gbps interface. I have the backups set to:

PARALLELLISM: 10
BUFFERSIZE: 10000

Buffer size is definitely working. I can observe 10000 document for each written batch id:

![screen shot 2018-11-29 at 7 36 25 pm](https://user-images.githubusercontent.com/1254810/49262911-13943680-f40e-11e8-9a50-763be0c4990d.png)

Parallelism just seems broken. I have it set for 10 processes but there are only 9. Additionally, only one of them is doing any serious work as evidenced from htop:

![proc](https://user-images.githubusercontent.com/1254810/49262967-476f5c00-f40e-11e8-97cf-023bb77c5340.gif)

**Comment by smithsz** [comment]
Hi @wmbutler,
Just to reiterate https://github.com/cloudant/couchbackup/issues/214#issuecomment-379712886, couchbackup does _not_ spawn additional OS processes for parallelism. The parallelism is for in-flight HTTP requests. I don't know where your additional couchbackup processes are coming from, but they aren't spawned by couchbackup itself.

Thank you for providing the complete CLI options. The problem is the use of "shallow mode". It doesn't use the `---parallelism` option. Under the hood it's just a single `/all_docs?include_docs=true` HTTP request. The "full backup" mode is different. It fetches all database changes (via `/_changes`) and adds them to an internal queue. We then initialise N workers (configured by the `---parallelism` option) to fetch the document revisions. So parallelism in the "full backup" case is really the number of in-flight HTTP requests when fetching document revisions.

Apologies for not spotting that first time round. We'll leave the ticket open to improve the documentation and option validation so that it is more clear that parallelism doesn't apply for "shallow mode" backups.

Let me know if you have further questions.

Thanks.

**Comment by wmbutler** [comment]
Turning off shallow mode did the trick. I'm seeing backups happen at 10x speed now. Nice! I also issued a PR for updating the readme on the shallow mode option.

**Comment by wmbutler** [comment]
I've turned off shallow mode and am observing the performance. The machine is still decidedly idle. My script appears to be populating the *.log file while backing up. Does it then generate the named backup file set in the command line argument?

Is there any chance you could walk through the process that script takes to better understand this?

> What's in a backup file?
A backup file is a text file where each line contains a JSON encoded array of up to buffer-size objects e.g.

    [{"a":1},{"a":2}...]
    [{"a":501},{"a":502}...]
>What's in a log file?
A log file contains a line:

>for every batch of document ids that need to be fetched e.g. :t batch56 [{"id":"a"},{"id":"b"}]
for every batch that has been fetched and stored e.g. :d batch56
to indicate that the changes feed was fully consumed e.g. :changes_complete

**Comment by ricellis** [comment]
>Is there any chance you could walk through the process that script takes to better understand this?

The log file is written to throughout the full mode backup process.
The first phase of the full mode backup is to stream the `_changes` endpoint, this is what is being written to the log file initially (the changes are not written to the backup file itself). Once the end of the changes feed has been reached the "point in time" for the backup is fixed and couchbackup will start fetching all the batches of document revisions (via `_bulk_get`) that were reported by the changes feed, recording the batches as done in the log file at the same time as writing the documents to the backup file.

>How large should my backup file be relative to my db on cloudant. Am i correct to assume that if I have a lot of stored indexes, the backup file will be much smaller because it's not storing the contents of the indexes?

It is correct that indexes are not stored. CouchDB/Cloudant use some compression. In my experience the size reported by Cloudant is smaller than the uncompressed backup file, but larger than a gzip backup file.

**Comment by wmbutler** [comment]
Really appreciate that rundown. That's what I observed as I wrote the incremental stuff this weekend.
