### ISSUE TITLE
Backup design documents only?

### ISSUE THREAD

**Issue by jthomas** [cloudant/couchbackup#267]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Feature Request Description

Is it possible to filter the exported database documents to only include "design" documents? 

I want to use it to manage initialising new Cloudant instances with the correct databases and design documents from CI/CD environments. I don't want to have all the exported documents in the backup file, just those design docs. I can then use the backfile with the restore tool to ensure new DBs are initialised correctly.

**Comment by ricellis** [comment]
> Is it possible to filter the exported database documents to only include "design" documents?

There is no built-in functionality for doing this and it's not something we will add to couchbackup.

However, it is your backup file and you can modify it in anyway you want (but obviously you're on your own once you start "hand-crafting" a backup file). The [basic structure](https://github.com/cloudant/couchbackup#whats-in-a-backup-file) is briefly described in the README and I'm sure you can see from existing backups that the objects in the arrays are documents plus embedded revision information. If you want to iterate the lines then arrays of your backup file and strip out non-design docs and write a new file you could do that.

Alternatively you could set up a continuous [replication with a selector](https://console.bluemix.net/docs/services/Cloudant/api/replication.html#the-selector-field) to copy just the design documents into another new database and then backup just that database.

FWIW though I think the more common solution to this problem is to keep design documents in source control and check them out for deployment.

**Comment by glynnbird** [comment]
If you want to keep your pre-existing design documents in a file format that is compatible with `couchbackup`/`couchrestore` you can use a combination of `curl` and [jq](https://stedolan.github.io/jq/)

```sh
curl "$URL/cities/_all_docs?inclusive_end=false&start_key=%22_design%22&end_key=%22_design0%22&include_docs=true" | jq -c ".rows | map(. = .doc)"
```

That is :

- fetch all the documents (including the document body) between keys `_design/` --> `_design0/` (this is what the Cloudant dashboard does to fetch only the design docs)
- process the JSON with `jq` to return a flat array of just the document bodies

**Comment by jthomas** [comment]
Thanks for the explanations - that makes sense.
